Aplikacija/Cassandra_GreatReads/Cassandra_GreatReads/Models/AutorData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cassandra;
using Cassandra_GreatReads.Controllers;

namespace Cassandra_GreatReads.Models
{
    public class Autor
    {
        public int ID_Autora;
        public String Ime_Prezime;
        public LocalDate Godina_rođena;
        public LocalDate Godina_smrti;
        public String Zemlja;
        public String Biografija;
        public int Broj_knjiga;
        public float Prosecna_ocena;
    }
    public class AutorData
    {
        public List<Autor> Autori = new List<Autor>();

        public AutorData()
        {
            try
            {
                var cluster = Cluster.Builder().AddContactPoint("127.0.0.1").Build();
                using var session = cluster.Connect("greatreads");
                var results = session.Execute("select * from autor");
                Autor tmpObj = null;

                foreach (var result in results)
                {
                    tmpObj = new Autor();

                    tmpObj.ID_Autora = result.GetValue<int>("id_autora");
                    tmpObj.Ime_Prezime = result.GetValue<String>("ime_i_prezime");
                    tmpObj.Godina_rođena = result.GetValue<LocalDate>("godina_rodjenja");
                    tmpObj.Godina_smrti = result.GetValue<LocalDate>("godina_smrti");
                    tmpObj.Zemlja = result.GetValue<String>("zemlja_porekla");
                    tmpObj.Biografija = result.GetValue<String>("biografija");
                    tmpObj.Broj_knjiga = result.GetValue<int>("broj_knjiga");
                    tmpObj.Prosecna_ocena = result.GetValue<float>("prosecna_ocena");

                    Autori.Add(tmpObj);
                }
            }
            catch (Exception ex)
            {
            }
        }
    }
}

Aplikacija/Cassandra_GreatReads/Cassandra_GreatReads/Controllers/AutorDataController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cassandra_GreatReads.Models;
using Cassandra;
using System.Globalization;


namespace Cassandra_GreatReads.Controllers
{
    public class AutorDataController : Controller
    {
        ISession session = null;

        public AutorDataController()
        {
            try
            {
                var cluster = Cluster.Builder().AddContactPoint("127.0.0.1").Build();
                session = cluster.Connect("greatreads");
            }
            catch (Exception ex)
            { }
        }
        public IActionResult DisplayAutorData()
        {
            AutorData ad = new AutorData();
            return View(ad);
        }

        public IActionResult GoToCreateAutor(int id_autora)
        {
            if (id_autora != 0)
            {
                Autor tmpObj = null;

                try
                {
                    var results = session.Execute("SELECT * FROM autor WHERE " +
                                    "id_autora =" + id_autora + " ; ");

                    foreach (var result in results)
                    {
                        tmpObj = new Autor();

                        tmpObj.ID_Autora = result.GetValue<int>("id_autora");
                        tmpObj.Ime_Prezime = result.GetValue<String>("ime_i_prezime");
                        tmpObj.Godina_rođena = result.GetValue<LocalDate>("godina_rodjenja");
                        tmpObj.Godina_smrti = result.GetValue<LocalDate>("godina_smrti");
                        tmpObj.Zemlja = result.GetValue<String>("zemlja_porekla");
                        tmpObj.Biografija = result.GetValue<String>("biografija");
                        tmpObj.Broj_knjiga = result.GetValue<int>("broj_knjiga");
                        tmpObj.Prosecna_ocena = result.GetValue<float>("prosecna_ocena");
                    }
                }
                catch (Exception ex) { }

                return View(tmpObj);
            }
            else
                return View();
        }

        private Boolean CheckAutor(Autor autor)
        {
            if (autor.ID_Autora == 0)
                return false;
            return true;
        }

        public IActionResult SaveAutor(int id_autora, String ime_prezime, DateTime godina_rođenja, DateTime godina_smrti,
            String zemlja, int broj_knjiga, float prosecna_ocena, String biografija)
        {
            Autor kObj = new Autor();

            kObj.ID_Autora = id_autora;
            kObj.Ime_Prezime = ime_prezime;
            kObj.Godina_rođena = new LocalDate(godina_rođenja.Year,godina_rođenja.Month,godina_rođenja.Day);
            kObj.Godina_smrti = new LocalDate(godina_smrti.Year, godina_smrti.Month, godina_smrti.Day);
            kObj.Zemlja = zemlja;
            kObj.Broj_knjiga = broj_knjiga;
            kObj.Biografija = biografija;
            kObj.Prosecna_ocena = prosecna_ocena;

            if (!CheckAutor(kObj))
                return RedirectToAction("DisplayAutorData");

            LocalDate localDate = null;
            LocalDate minLD = new LocalDate(1, 1, 1);
            if (kObj.Godina_smrti == minLD)
                localDate = new LocalDate(9999, 12, 31);
            else
                localDate = new LocalDate(kObj.Godina_smrti.Year, kObj.Godina_smrti.Month, kObj.Godina_smrti.Day);

            LocalDate localDate1 = null;
            LocalDate minLD1 = new LocalDate(1, 1, 1);
            if (kObj.Godina_rođena == minLD1)
                localDate1 = new LocalDate(1000, 10, 10);
            else
                localDate1 = new LocalDate(kObj.Godina_rođena.Year, kObj.Godina_rođena.Month, kObj.Godina_rođena.Day);


            try
            {
                session.Execute("INSERT INTO autor (id_autora, ime_i_prezime, godina_rodjenja, godina_smrti, zemlja_porekla," +
                                "broj_knjiga, prosecna_ocena, biografija)" +
                                "VALUES (" + kObj.ID_Autora +
                                ", \'" + kObj.Ime_Prezime + "\'" +
                                ", \'" + localDate1.ToString() + "\'" +
                                ", \'" + localDate.ToString() + "\'" +
                                ", \'" + kObj.Zemlja + "\'" +
                                ", " + kObj.Broj_knjiga +
                                ", " + kObj.Prosecna_ocena +
                                ", \'" + kObj.Biografija + "\');");
            }
            catch (Exception ex) { }
            return RedirectToAction("DisplayAutorData");
        }

        public IActionResult DeleteAutor(int id_autora)
        {
            try
            {
                session.Execute("DELETE FROM autor WHERE " +
                                "id_autora =" + id_autora + " ; ");
            }
            catch (Exception ex) { }

            return RedirectToAction("DisplayAutorData");
        }

        public IActionResult UpdateAutor(int id_autora)
        {
            return RedirectToAction("GoToCreateAutor", new { id_autora = id_autora });
        }

        public IActionResult DodajKnjiguAutoru(int id_autora)
        {
            return View(id_autora);
        }
    }
}

Aplikacija/Cassandra_GreatReads/Cassandra_GreatReads/Controllers/KnjigeAutoraDataController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cassandra_GreatReads.Models;
using Cassandra;
using System.Globalization;

namespace Cassandra_GreatReads.Controllers
{
    public class KnjigeAutoraDataController : Controller
    {
        ISession session = null;

        public KnjigeAutoraDataController()
        {
            try
            {
                var cluster = Cluster.Builder().AddContactPoint("127.0.0.1").Build();
                session = cluster.Connect("greatreads");
            }
            catch (Exception ex)
            { }
        }
        public IActionResult DisplayKnjigeAutoraData()
        {
            KnjigeAutoraData okd = new KnjigeAutoraData();
            return View(okd);
        }

        public Boolean CheckKnjiga(KnjigaAutora KnjigaAutora)
        {
            if (KnjigaAutora.ID_Knjige == 0 || KnjigaAutora.ID_Autora == 0)
                return false;
            return true;
        }

        public IActionResult DeleteKnjigaAutora(int id_knjige, int id_autora)
        {
            try
            {
                session.Execute("DELETE FROM knjigeautora WHERE " +
                                "id_knjige =" + id_knjige + " and " +
                                "id_autora =" + id_autora + ";");
            }
            catch (Exception ex)
            {

            }

            int broj_knjiga;

            var bk = session.Execute("Select broj_knjiga from autor where id_autora=" + id_autora + ";");
            broj_knjiga = bk.First().GetValue<int>(0);
            broj_knjiga--;

            session.Execute("update autor set broj_knjiga=" + broj_knjiga + " where id_autora=" + id_autora + ";");

            return RedirectToAction("DisplayKnjigeAutoraData");
        }

        public IActionResult GoToCreateKnjigaAutora(int id_knjige, int id_autora)
        {
            if (id_knjige != 0 && id_autora != 0)
            {
                KnjigaAutora tmpObj = null;

                try
                {
                    var results = session.Execute("SELECT * FROM knjigeautora WHERE " +
                                  "id_knjige =" + id_knjige + " and " +
                                  "id_autora = " + id_autora + ";");

                    foreach (var result in results)
                    {
                        tmpObj = new KnjigaAutora();

                        tmpObj.ID_Knjige = result.GetValue<int>("id_knjige");
                        tmpObj.ID_Autora = result.GetValue<int>("id_autora");
                        tmpObj.Naslov = result.GetValue<String>("naslov");
                    }
                }
                catch (Exception ex)
                {

                }

                return View(tmpObj);
            }

            return View();
        }

        public IActionResult SaveKnjigaAutora(int id_knjige, int id_autora)
        {

            KnjigaAutora oObj = new KnjigaAutora();

            oObj.ID_Knjige = id_knjige;
            oObj.ID_Autora = id_autora;

            if (!CheckKnjiga(oObj))
                return RedirectToAction("DisplayKnjigeAutoraData");

            var knjiga = session.Execute("select naslov from knjiga where id_knjige=" + id_knjige + ";").First();

            oObj.Naslov = knjiga.GetValue<String>(0);

            try
            {
                session.Execute("INSERT INTO knjigeautora (id_knjige, id_autora, naslov) " +
                    "VALUES (" + oObj.ID_Knjige +
                    ", " + oObj.ID_Autora +
                    ", \'" + oObj.Naslov + "\');");
            }
            catch (Exception ex)
            {

            }

            int broj_knjiga;

            var bk = session.Execute("Select broj_knjiga from autor where id_autora=" + id_autora + ";");
            broj_knjiga = bk.First().GetValue<int>(0);
            broj_knjiga++;

            session.Execute("update autor set broj_knjiga=" + broj_knjiga + " where id_autora=" + id_autora + ";");

            return RedirectToAction("DisplayKnjigeAutoraData");
        }

    }
}

Aplikacija/Cassandra_GreatReads/Cassandra_GreatReads/Views/AutorData/DisplayAutorData.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Cassandra_GreatReads.Models.AutorData

@{
    ViewBag.Title = "Lista autora";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="display:flex; flex-direction:column">
    <h2>Prikaz liste autora</h2>
    <a asp-area="" asp-action="GoToCreateAutor" asp-controller="AutorData" style="margin-bottom:50px; max-width:200px;">
        <button>Dodaj autora</button>
    </a>

    <table border="1" align="left" style="max-width:1600px; text-align:center;">
        <thead>
            <tr>
                <td width="200">ID_Autora</td>
                <td width="200">Ime_Prezime</td>
                <td width="200">Godina_rođena</td>
                <td width="200">Godina_smrti</td>
                <td width="300">Zemlja</td>
                <td width="200">Broj_knjiga</td>
                <td width="200">Prosecna_ocena</td>
                <td width="200"></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var v in Model.Autori)
            {
                <tr>
                    <td>@v.ID_Autora</td>
                    <td>@v.Ime_Prezime</td>
                    <td>@v.Godina_rođena</td>
                    <td>@v.Godina_smrti</td>
                    <td>@v.Zemlja</td>
                    <td>@v.Broj_knjiga</td>
                    <td>@v.Prosecna_ocena</td>
                    <td>
                        <form action="DeleteAutor" method="post">
                            <input type="text" name="id_autora" placeholder="id_autora" value="@v.ID_Autora" hidden="hidden" />
                            <input style="width:100%" type="submit" value="Obriši autora" />
                        </form>
                        <form action="UpdateAutor" method="post">
                            <input type="text" name="id_autora" placeholder="id_autora" value="@v.ID_Autora" hidden="hidden" />
                            <input style="width:100%" type="submit" value="Izmeni autora" />
                        </form>
                        <form action="DodajKnjiguAutoru" method="post">
                            <input type="text" name="id_autora" placeholder="id_autora" value="@v.ID_Autora" hidden="hidden" />
                            <input style="width:100%" type="submit" value="Dodaj knjigu autoru" />
                        </form>
                    </td>
                </tr>
                <tr>
                    <td colspan="8" align="center"><b>Biografija</b></td>
                </tr>
                <tr style="text-align:left">
                    <td colspan="8">@v.Biografija</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Aplikacija/Cassandra_GreatReads/Cassandra_GreatReads/Views/AutorData/DodajKnjiguAutoru.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model int

@{
    ViewBag.Title = "Kreiraj autora";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="display:flex; flex-direction:column">
    <h2 style="margin-bottom:50px;">Dodajte knjigu autoru</h2>
    <form asp-action="SaveKnjigaAutora" asp-controller="KnjigeAutoraData" method="post">
        <label style="margin-right:10px;">ID Knjige</label>
        <input type="text" name="id_autora" placeholder="id_autora" value="@Model" hidden="hidden" />
        <input type="text" name="id_knjige" placeholder="id_knjige" />
        <input type="submit" value="Dodaj knjigu autoru" style="margin-left:25px;" />
    </form>
</div>

Aplikacija/Cassandra_GreatReads/Cassandra_GreatReads/Views/AutorData/GoToCreateAutor.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Cassandra_GreatReads.Models.Autor

@{
    ViewBag.Title = "Kreiraj autora";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model == null)
{
    <div>
        <form action="SaveAutor" method="post">
            <label>ID Autora</label>
            <input type="text" name="id_autora" placeholder="id_autora" />
            <br />
            <label>Ime i prezime</label>
            <input type="text" name="ime_prezime" placeholder="ime_prezime" />
            <br />
            <label>Datum rođenja</label>
            <input type="date" name="godina_rođenja" placeholder="godina_rođenja" />
            <br />
            <label>Datum smrti</label>
            <input type="date" name="godina_smrti" placeholder="godina_smrti" />
            <br />
            <label>Zemlja</label>
            <input type="text" name="zemlja" placeholder="zemlja" />
            <br />
            <label>Biografija</label>
            <input type="text" name="biografija" placeholder="biografija" />
            <br />
            <input type="submit" value="Sačuvaj Autora" />
        </form>
    </div>
}
else
{
    <div>
        <form action="SaveAutor" method="post">
            <label hidden="hidden">ID Autora</label>
            <input hidden="hidden" type="text" name="id_autora" placeholder="id_autora" value="@Model.ID_Autora"/>
            <br />
            <label>Ime i prezime</label>
            <input type="text" name="ime_prezime" placeholder="ime_prezime" value="@Model.Ime_Prezime"/>
            <br />
            <label>Datum rođenja</label>
            <input type="date" name="godina_rođenja" placeholder="godina_rođenja" value="@Model.Godina_rođena.ToString()"/>
            <br />
            <label>Datum smrti</label>
            <input type="date" name="godina_smrti" placeholder="godina_smrti" value="@Model.Godina_smrti.ToString()"/>
            <br />
            <label>Zemlja</label>
            <input type="text" name="zemlja" placeholder="zemlja" value="@Model.Zemlja"/>
            <br />
            <label>Broj knjiga</label>
            <input type="text" name="broj_knjiga" placeholder="broj_knjiga" value="@Model.Broj_knjiga"/>
            <br />
            <label>Prosečna ocena</label>
            <input type="text" name="prosecna_ocena" placeholder="prosecna_ocena" value="@Model.Prosecna_ocena"/>
            <br />
            <label>Biografija</label>
            <input type="text" name="biografija" placeholder="biografija" value="@Model.Biografija"/>
            <br />
            <input type="submit" value="Sačuvaj Autora" />
        </form>
    </div>
}