Aplikacija/Cassandra_GreatReads/Cassandra_GreatReads/Models/Korisnik.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cassandra;

namespace Cassandra_GreatReads.Models
{
    public class Korisnik
    {
        public int ID_Korisnika { get; set; }
        public string Email { get; set; }
        public LocalDate God_rodjenja { get; set; }
        public string Ime_i_prezime { get; set; }
        public string Lozinka { get; set; }
        public string Pol { get; set; }

        public string Username { get; set; }

    }

    public class KorisnikData
    {
        public IList<Korisnik> Korisnici = new List<Korisnik>();

        public KorisnikData()
        {
            try
            {
                var cluster = Cluster.Builder().AddContactPoint("127.0.0.1").Build();
                using var session = cluster.Connect("greatreads");
                var results = session.Execute("select * from korisnik");
                Korisnik kor = null;

                foreach(var rez in results)
                {
                    kor = new Korisnik();
                    kor.ID_Korisnika = rez.GetValue<int>("id_korisnika");
                    kor.Email = rez.GetValue<string>("email");
                    kor.God_rodjenja = rez.GetValue<LocalDate>("godina_rodjenja");
                    kor.Ime_i_prezime = rez.GetValue<string>("ime_i_prezime");
                    kor.Lozinka = rez.GetValue<string>("lozinka");
                    kor.Pol = rez.GetValue<string>("pol");
                    kor.Username = rez.GetValue<string>("username");

                    Korisnici.Add(kor);
                }

            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

        }
    }



}

Aplikacija/Cassandra_GreatReads/Cassandra_GreatReads/Controllers/KorisnikController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cassandra_GreatReads.Models;
using Cassandra;

namespace Cassandra_GreatReads.Controllers
{
    public class KorisnikController : Controller
    {
        ISession session = null;

        public KorisnikController()
        {
            try
            {
                var cluster = Cluster.Builder().AddContactPoint("127.0.0.1").Build();
                session = cluster.Connect("greatreads");
            }
            catch (Exception ex)
            { }
        }
        public IActionResult DisplayKorisnikData()
        {
            KorisnikData kor = new KorisnikData();
            return View(kor);
        }

        public IActionResult GoToCreateKorisnik(int id_korisnika)
        {
            if (id_korisnika != 0)
            {
                Korisnik kor=null;
                try
                {
                    var results = session.Execute("SELECT * FROM korisnik WHERE " +
                                    "id_korisnika =" + id_korisnika + " ; ");
            
                    foreach (var rez in results)
                    {
                        kor = new Korisnik();
                        kor.ID_Korisnika = rez.GetValue<int>("id_korisnika");
                        kor.Email = rez.GetValue<string>("email");
                        kor.God_rodjenja = rez.GetValue<LocalDate>("godina_rodjenja");
                        kor.Ime_i_prezime = rez.GetValue<string>("ime_i_prezime");
                        kor.Lozinka = rez.GetValue<string>("lozinka");
                        kor.Pol = rez.GetValue<string>("pol");
                        kor.Username = rez.GetValue<string>("username");

                    
                    }

                }
                catch (Exception ex) { }
                return View(kor);
            }
            else
                return View();
        }


        public bool CheckKorisnik(Korisnik k)
        {
            if (k.ID_Korisnika == 0)
                return false;
            return true;
        }

        public IActionResult SaveKorisnik(int id_korisnika, string email, DateTime godina_rodjenja, string ime_i_prezime
            , string lozinka, string pol, string username)
        {
            Korisnik kor = new Korisnik();
            kor.ID_Korisnika = id_korisnika;
            kor.Email = email;
            kor.God_rodjenja = new LocalDate(godina_rodjenja.Year, godina_rodjenja.Month, godina_rodjenja.Day);
            kor.Ime_i_prezime = ime_i_prezime;
            kor.Lozinka = lozinka;
            kor.Pol = pol;
            kor.Username = username;
            
            if(!CheckKorisnik(kor))
                return RedirectToAction("DisplayKorisnikData");
            LocalDate localDate = null;
            LocalDate minLD = new LocalDate(1, 1, 1);
            if (kor.God_rodjenja == minLD)
                localDate = new LocalDate(1000, 10, 10);
            else
                localDate = new LocalDate(kor.God_rodjenja.Year, kor.God_rodjenja.Month, kor.God_rodjenja.Day);

            try
            {              
                session.Execute("INSERT INTO korisnik(id_korisnika, email, godina_rodjenja, ime_i_prezime, lozinka, pol, username)" +
                                "VALUES (" + kor.ID_Korisnika +
                                ", \'" + kor.Email + "\'" +
                                ", \'" + localDate.ToString() + "\'" +
                                ", \'" +kor.Ime_i_prezime + "\'" +
                                ", \'" + kor.Lozinka + "\'" +
                                ", \'" + kor.Pol + "\'"+
                                ",\' " + kor.Username + "\');");
            }
            catch (Exception ex) { Console.WriteLine(ex.Message); }
            return RedirectToAction("DisplayKorisnikData");

        }


        public IActionResult DeleteKorisnik (int id_korisnika)
        {
            try
            {
                session.Execute("DELETE FROM korisnik WHERE " +
                                "id_korisnika = " + id_korisnika + " ; ");
            }
            catch (Exception ex) { Console.WriteLine(ex.Message); }

            return RedirectToAction("DisplayKorisnikData");
        }

        public IActionResult UpdateKorisnik (int id_korisnika)
        {
            return RedirectToAction("GoToCreateKorisnik", new { id_korisnika = id_korisnika });
        }

        public IActionResult PogledajPolice (int id_korisnika)
        {
            return RedirectToAction("DisplayPolicaData", "Polica", new { id_korisnika = id_korisnika });
        }

    }
}

Aplikacija/Cassandra_GreatReads/Cassandra_GreatReads/Views/Korisnik/DisplayKorisnikData.cshtml
@model Cassandra_GreatReads.Models.KorisnikData

@{
    ViewData["Title"] = "Lista korisnika";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div style="display:flex; flex-direction:column">
    <h1>Prikaz liste korisnika</h1>
    <a asp-area="" asp-action="GoToCreateKorisnik" asp-controller="Korisnik" style="margin-bottom:50px; max-width:200px;">
        <button>Dodaj korisnika</button>
    </a>
    <table border="1" align="left" style="max-width:1600px; text-align:center;">
        <thead>

            <tr>
                <td width="200">ID_Korisnika</td>
                <td width="200">Ime_i_prezime</td>
                <td width="200">Godina_rođenja</td>
                <td width="200">Email</td>
                <td width="300">Username</td>
                <td width="200">Lozinka</td>
                <td width="200">Pol</td>

                <td width="200"></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var v in Model.Korisnici)
            {


                <tr>
                    <td>@v.ID_Korisnika</td>
                    <td>@v.Ime_i_prezime</td>
                    <td>@v.God_rodjenja</td>
                    <td>@v.Email</td>
                    <td>@v.Username</td>
                    <td>@v.Lozinka.GetHashCode()</td>
                    <td>@v.Pol</td>

                    <td>
                        <form action="DeleteKorisnik" method="post">
                            <input type="text" name="id_korisnika" placeholder="id_korisnika" value="@v.ID_Korisnika" hidden="hidden" />
                            <input style="width:100%" type="submit" value="Obriši korisnika" />
                        </form>
                        <form action="UpdateKorisnik" method="post">
                            <input type="text" name="id_korisnika" placeholder="id_korisnika" value="@v.ID_Korisnika" hidden="hidden" />
                            <input style="width:100%" type="submit" value="Izmeni korisnika" />
                        </form>
                        <form action="PogledajPolice" method="get">
                            <input type="text" name="id_korisnika" placeholder="id_korisnika" value="@v.ID_Korisnika" hidden="hidden" />
                            <input style="width:100%" type="submit" value="Pogledaj police korisnika" />
                        </form>
                    </td>
                </tr>



            }
        </tbody>
    </table>
</div>

Aplikacija/Cassandra_GreatReads/Cassandra_GreatReads/Views/Korisnik/GoToCreateKorisnik.cshtml
@model Cassandra_GreatReads.Models.Korisnik

@{
    ViewData["Title"] = "Kreiraj Korisnika";
}


@if (Model == null)
{
    <div>
        <form action="SaveKorisnik" method="post">
            <label>ID_Korisnika</label>
            <input type="text" name="id_korisnika" placeholder="id_korisnika" />
            <br />
            <label>Email</label>
            <input type="text" name="email" placeholder="email" />
            <br />
            <label>God_rodjenja</label>
            <input type="date" name="godina_rodjenja" placeholder="godina_rodjenja" />
            <br />
            <label>Ime_i_prezime</label>
            <input type="text" name="ime_i_prezime" placeholder="ime_i_prezime" />
            <br />
            <label>Lozinka</label>
            <input type="password" name="lozinka" placeholder="lozinka" />
            <br />
            <label>Pol</label>
            <input type="text" name="pol" placeholder="pol" />
            <br />
            <label>Username</label>
            <input type="text" name="username" placeholder="username" />
            <br />

            <input type="submit" value="Sačuvaj Korisnika" />
        </form>
    </div>
}
else
{
    <div>
        <form action="SaveKorisnik" method="post">
            <label hidden="hidden">ID_Korisnika</label>
            <input hidden="hidden" type="text" name="id_korisnika" placeholder="id_korisnika" value="@Model.ID_Korisnika" />
            <br />
            <label>Email</label>
            <input type="text" name="email" placeholder="email" value="@Model.Email" />
            <br />
            <label>God_rodjenja</label>
            <input type="date" name="godina_rodjenja" placeholder="godina_rodjenja" value="@Model.God_rodjenja" />
            <br />
            <label>Ime_i_prezime</label>
            <input type="text" name="ime_i_prezime" placeholder="ime_i_prezime" value="@Model.Ime_i_prezime" />
            <br />
            <label>Lozinka</label>
            <input type="password" name="lozinka" placeholder="lozinka" value="@Model.Lozinka"/>
            <br />
            <label>Pol</label>
            <input type="text" name="pol" placeholder="pol" value="@Model.Pol" />
            <br />
            <label>Username</label>
            <input type="text" name="username" placeholder="username" value="@Model.Username" />
            <br />

            <input type="submit" value="Sačuvaj Korisnika" />
        </form>
    </div>
}