Aplikacija/Cassandra_GreatReads/Cassandra_GreatReads/Controllers/KnjigaDataController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cassandra_GreatReads.Models;
using Cassandra;
using System.Globalization;


namespace Cassandra_GreatReads.Controllers
{
    public class KnjigaDataController : Controller
    {
        ISession session = null;

        public KnjigaDataController()
        {
            try
            {
                var cluster = Cluster.Builder().AddContactPoint("127.0.0.1").Build();
                session = cluster.Connect("greatreads");
            }
            catch (Exception ex)
            { }
        }
        public IActionResult DisplayKnjigaData()
        {
            KnjigaData kd = new KnjigaData();
            return View(kd);
        }

        public IActionResult GoToCreateKnjiga(int  id_knjige)
        {
            if (id_knjige != 0)
            {
                Knjiga tmpObj = null;

                try
                {
                    var results = session.Execute("SELECT * FROM knjiga WHERE " +
                                    "id_knjige =" + id_knjige + " ; ");

                    foreach (var result in results)
                    {
                        tmpObj = new Knjiga();

                        tmpObj.ID_Knjige = result.GetValue<int>("id_knjige");
                        tmpObj.Naslov = result.GetValue<String>("naslov");
                        tmpObj.Naslov_originala = result.GetValue<String>("naslov_originala");
                        tmpObj.Autor = result.GetValue<String>("autor");
                        tmpObj.Broj_stranica = result.GetValue<int>("broj_stranica");
                        tmpObj.Format_knjige = result.GetValue<String>("format_knjige");
                        tmpObj.Godina_izdavanja = result.GetValue<LocalDate>("godina_izdavanja");
                        tmpObj.Jezik = result.GetValue<String>("jezik");
                        tmpObj.Prosecna_ocena = result.GetValue<float>("prosecna_ocena");
                        tmpObj.Zanr = result.GetValue<String>("zanr");
                    }
                }
                catch (Exception ex) { }

                return View(tmpObj);
            }
            else
                return View();
        }

        private Boolean CheckKnjiga(Knjiga knjiga)
        {
            if (knjiga.ID_Knjige == 0)
                return false;
            return true;
        }

        public IActionResult SaveKnjiga(int id_knjige, String naslov, String naslov_originala, String autor, DateTime godina_izdavanja,
            String format_knjige, String jezik, String zanr, int broj_stranica, float prosecna_ocena)
        {
            Knjiga kObj = new Knjiga();

            kObj.ID_Knjige = id_knjige;
            kObj.Naslov = naslov;
            kObj.Naslov_originala = naslov_originala;
            kObj.Autor = autor;
            kObj.Godina_izdavanja = new LocalDate(godina_izdavanja.Year,godina_izdavanja.Month,godina_izdavanja.Day);
            kObj.Format_knjige = format_knjige;
            kObj.Jezik = jezik;
            kObj.Zanr = zanr;
            kObj.Broj_stranica = broj_stranica;
            kObj.Prosecna_ocena = prosecna_ocena;

            if(!CheckKnjiga(kObj))
                return RedirectToAction("DisplayKnjigaData");

            LocalDate localDate = null;
            LocalDate minLD = new LocalDate(1, 1, 1);
            if (kObj.Godina_izdavanja == minLD)
                localDate = new LocalDate(1000, 10, 10);
            else
                localDate = new LocalDate(kObj.Godina_izdavanja.Year, kObj.Godina_izdavanja.Month, kObj.Godina_izdavanja.Day);
            
            try
            {
                session.Execute("INSERT INTO knjiga (id_knjige, naslov, naslov_originala, autor, godina_izdavanja," +
                                "format_knjige, jezik, zanr, broj_stranica, prosecna_ocena)" +
                                "VALUES (" + kObj.ID_Knjige +
                                ", \'" + kObj.Naslov + "\'" +
                                ", \'" + kObj.Naslov_originala + "\'" +
                                ", \'" + kObj.Autor + "\'" +
                                ", \'" + localDate.ToString() + "\'" +
                                ", \'" + kObj.Format_knjige + "\'" +
                                ", \'" + kObj.Jezik + "\'" +
                                ", \'" + kObj.Zanr + "\'" +
                                ", " + kObj.Broj_stranica +
                                ", " + kObj.Prosecna_ocena + ");");
            }
            catch(Exception ex) { }
            return RedirectToAction("DisplayKnjigaData");
        }

        public IActionResult DeleteKnjiga(int id_knjige)
        {
            try
            {
                session.Execute("DELETE FROM knjiga WHERE " +
                                "id_knjige =" + id_knjige + " ; ");
            }
            catch(Exception ex) { }

            return RedirectToAction("DisplayKnjigaData");
        }

        public IActionResult UpdateKnjiga(int id_knjige)
        {
            return RedirectToAction("GoToCreateKnjiga", new { id_knjige = id_knjige });
        }
    }
}

Aplikacija/Cassandra_GreatReads/Cassandra_GreatReads/Controllers/OceneKorisnikaDataController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cassandra_GreatReads.Models;
using Cassandra;
using System.Globalization;

namespace Cassandra_GreatReads.Controllers
{
    public class OceneKorisnikaDataController : Controller
    {
        ISession session = null;

        public OceneKorisnikaDataController()
        {
            try
            {
                var cluster = Cluster.Builder().AddContactPoint("127.0.0.1").Build();
                session = cluster.Connect("greatreads");
            }
            catch (Exception ex)
            { }
        }
        public IActionResult DisplayOceneKorisnikaData()
        {
            OceneKorisnikaData okd = new OceneKorisnikaData();
            return View(okd);
        }

        public Boolean CheckOcena(OceneKorisnika ocena)
        {
            if (ocena.ID_Knjige == 0 || ocena.ID_Korisnika == 0)
                return false;
            return true;
        }

        public IActionResult DeleteOcena(int id_knjige, int id_korisnika)
        {
            try
            {
                session.Execute("DELETE FROM ocenekorisnika WHERE " +
                                "id_knjige =" + id_knjige + " and " +
                                "id_korisnika =" + id_korisnika + ";");
            }
            catch(Exception ex)
            {

            }
            RacunajProsekOcena(id_knjige);
            RacunajProsekAutora(id_knjige);
            return RedirectToAction("DisplayOceneKorisnikaData");
        }

        public IActionResult GoToCreateOcena(int id_knjige, int id_korisnika, int ocena)
        {
            OceneKorisnika tmpObj = null;

            tmpObj = new OceneKorisnika();

            tmpObj.ID_Knjige = id_knjige;
            tmpObj.ID_Korisnika = id_korisnika;
            tmpObj.Ocena = ocena;

            return View(tmpObj);
        }

        public IActionResult SaveOcena(int id_knjige, int id_korisnika, int ocena)
        {
            OceneKorisnika oObj = new OceneKorisnika();

            oObj.ID_Knjige = id_knjige;
            oObj.ID_Korisnika = id_korisnika;
            oObj.Ocena = ocena;

            if (!CheckOcena(oObj))
                return RedirectToAction("DisplayOceneKorisnikaData");

            try
            {
                session.Execute("INSERT INTO ocenekorisnika (id_knjige, id_korisnika, ocena) " +
                    "VALUES (" + oObj.ID_Knjige +
                    ", " + oObj.ID_Korisnika +
                    ", " + oObj.Ocena + ");");
            }
            catch (Exception ex)
            {

            }
            RacunajProsekOcena(id_knjige);
            RacunajProsekAutora(id_knjige);

            return RedirectToAction("DisplayOceneKorisnikaData");
        }

        private void RacunajProsekOcena(int id_knjige)
        {
            float suma = 0, n = 0;

            try
            {
                var ocene = session.Execute("Select ocena from ocenekorisnika where id_knjige=" + id_knjige + ";");

                foreach(var ocena in ocene)
                {
                    int ocn = ocena.GetValue<int>(0);
                    suma += ocn;
                    n++;
                }
                float prosek = suma / n;

                session.Execute("update knjiga set prosecna_ocena=" +
                                prosek.ToString("0.000", System.Globalization.CultureInfo.InvariantCulture) +
                                " where id_knjige=" + id_knjige + ";");
            }
            catch(Exception ex)
            { }
        }

        private void RacunajProsekAutora(int id_knjige)
        {
            float suma = 0, n = 0;
            try
            {
                var autor = session.Execute("select id_autora from knjigeautora where id_knjige=" + id_knjige + ";");

                int id_autora = autor.First().GetValue<int>("id_autora");

                var knjige = session.Execute("select id_knjige from knjigeautora where id_autora=" + id_autora + ";");

                foreach(var knjiga in knjige)
                {
                    int ids_knjige = knjiga.GetValue<int>(0);

                    var result = session.Execute("select prosecna_ocena from knjiga where id_knjige=" + ids_knjige + ";").FirstOrDefault();

                    float ocena = result.GetValue<float>(0);

                    suma += ocena;
                    n++;
                }

                float prosek = suma / n;

                session.Execute("update autor set prosecna_ocena=" +
                                prosek.ToString("0.000",System.Globalization.CultureInfo.InvariantCulture) +
                                " where id_autora=" +
                                id_autora + ";");
            }
            catch(Exception ex)
            { }
        }
    }
}

Aplikacija/Cassandra_GreatReads/Cassandra_GreatReads/Controllers/PolicaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cassandra_GreatReads.Models;
using Cassandra;

namespace Cassandra_GreatReads.Controllers
{
    public class PolicaController : Controller
    {
        ISession session = null;

        public PolicaController()
        {
            try
            {
                var cluster = Cluster.Builder().AddContactPoint("127.0.0.1").Build();
                session = cluster.Connect("greatreads");
            }
            catch(Exception ex)
            { }
        }
        public IActionResult DisplayPolicaData(int id_korisnika)
        {
            PolicaData pd = null;
            if(id_korisnika==0)
                pd = new PolicaData();
            else
                pd = new PolicaData(id_korisnika);
            return View(pd);
        }

        public IActionResult DisplayPolica(int id_police)
        {
            if (id_police != 0)
            {
                KnjigeNaPoliciData kp = new KnjigeNaPoliciData(id_police);
                return View(kp);
            }
            else
                return RedirectToAction("DisplayPolicaData");
        }

        public IActionResult GoToCreatePolica(int id_police)
        {
            if (id_police != 0)
            {
                Polica tmpObj = null;

                try
                {
                    var results = session.Execute("SELECT * FROM polica WHERE " +
                                    "id_police =" + id_police + " ; ");

                    foreach (var result in results)
                    {
                        tmpObj = new Polica();

                        tmpObj.ID_Police = result.GetValue<int>("id_police");
                        tmpObj.Naziv = result.GetValue<String>("naziv");
                        tmpObj.Broj_knjiga = result.GetValue<int>("broj_knjiga");
                    }
                }
                catch (Exception ex) { }

                return View(tmpObj);
            }
            else
                return View();
        }

        private Boolean CheckPolica(Polica polica)
        {
            if (polica.ID_Police == 0)
                return false;
            return true;
        }

        public IActionResult SavePolica(int id_police, String naziv, int id_korisnika)
        {
            int broj_knjiga = 0;
            try
            {
                var result = session.Execute("Select * from polica where id_police=" + id_police + ";");
                if (result.Count() != 0)
                    broj_knjiga = result.First().GetValue<int>("broj_knjiga");
            }
            catch(Exception ex)
            { }

            Polica kObj = new Polica();

            kObj.ID_Police = id_police;
            kObj.Naziv = naziv;
            kObj.Broj_knjiga = broj_knjiga;

            if (!CheckPolica(kObj))
                return RedirectToAction("DisplayPolicaData");

            var pk = session.Execute("select * from policekorisnika where id_police=" +
                                        id_police + " and id_korisnika=" + id_korisnika + ";");

            if(pk.Count()!=0)
                return RedirectToAction("DisplayPolicaData");

            try
            {
                session.Execute("INSERT INTO polica (id_police, naziv, broj_knjiga)" +
                                "VALUES (" + kObj.ID_Police +
                                ", \'" + kObj.Naziv + "\'" +
                                ", " + kObj.Broj_knjiga + ");");

                session.Execute("Insert into policekorisnika (id_korisnika, id_police) " +
                                "values (" + id_korisnika + ", " + id_police + ");");
            }
            catch (Exception ex) { }
            return RedirectToAction("DisplayPolicaData");
        }

        public IActionResult DeletePolica(int id_police)
        {
            try
            {
                session.Execute("delete from knjigenapolici where id_police=" + id_police + ";");
                var ids = session.Execute("select * from policekorisnika where id_police=" + id_police + ";");

                foreach(var id in ids)
                {
                    int id_korisnika = id.GetValue<int>("id_korisnika");

                    session.Execute("delete from policekorisnika where id_police = " + id_police +
                                    " and id_korisnika=" + id_korisnika + "; ");
                }

                session.Execute("DELETE FROM polica WHERE " +
                                "id_police =" + id_police + " ; ");                
            }
            catch (Exception ex) { }

            return RedirectToAction("DisplayPolicaData");
        }

        public IActionResult UpdatePolica(int id_police)
        {
            return RedirectToAction("GoToCreatePolica", new { id_police = id_police });
        }

        public IActionResult GoToDodajNaPolicu(int id_knjige)
        {
            PolicaData pd = new PolicaData();
            pd.id_knjige = id_knjige;
            return View(pd);
        }

        public IActionResult DodajNaPolicu(int id_knjige, int id_police)
        {
            if(id_knjige!=0 && id_police!=0)
            {
                var kp = session.Execute("select * from knjigenapolici where id_police=" + id_police +
                                        " and id_knjige=" + id_knjige + ";");

                if(kp.Count() != 0)
                    return RedirectToAction("DisplayPolicaData");
                try
                {
                    session.Execute("Insert into knjigenapolici (id_police, id_knjige)" +
                                    "values (" + id_police + ", " + id_knjige + ");");
                    var result = session.Execute("select * from polica where id_police=" + id_police + ";").First();
                    Polica p = new Polica();

                    p.Broj_knjiga = result.GetValue<int>("broj_knjiga");
                    p.Broj_knjiga++;

                    session.Execute("Update polica set broj_knjiga=" + p.Broj_knjiga + " where id_police=" + id_police + ";");
                }
                catch(Exception ex)
                { }
            }
            return RedirectToAction("DisplayPolicaData");
        }

        public IActionResult UkloniKnjigu(int id_police, int id_knjige)
        {
            int id_korisnika = 0;
            try
            {
                session.Execute("delete from knjigenapolici where id_police=" + id_police + " and id_knjige=" + id_knjige + ";");
                var polica = session.Execute("select * from polica where id_police=" + id_police + ";").First();

                Polica p = new Polica();

                p.Broj_knjiga = polica.GetValue<int>("broj_knjiga");
                p.Broj_knjiga--;

                session.Execute("update polica set broj_knjiga=" + p.Broj_knjiga + " where id_police=" + id_police+";");

                var korisnik = session.Execute("select id_korisnika from policekorisnika where id_police=" + id_police + ";").First();

                id_korisnika = korisnik.GetValue<int>(0);
            }
            catch(Exception ex)
            { }
            return RedirectToAction("DisplayPolicaData", new { id_korisnika = id_korisnika });
        }
    }
}

Aplikacija/Cassandra_GreatReads/Cassandra_GreatReads/Views/KnjigaData/DisplayKnjigaData.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Cassandra_GreatReads.Models.KnjigaData 

@{
    ViewBag.Title = "Lista knjiga";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="display:flex; flex-direction:column">
    <h2>Prikaz liste knjiga</h2>
    <a asp-area="" asp-action="GoToCreateKnjiga" asp-controller="KnjigaData" style="margin-bottom:50px; max-width:200px;">
        <button>Dodaj knjigu</button>
    </a>

    <table border="1" align="left" style="max-width:2200px; text-align:center;">
        <thead>
            <tr>
                <td width="200">ID_Knjige</td>
                <td width="200">Naslov</td>
                <td width="200">Naslov_originala</td>
                <td width="200">Autor</td>
                <td width="300">Godina_izdavanja</td>
                <td width="200">Format_knjige</td>
                <td width="200">Jezik</td>
                <td width="200">Zanr</td>
                <td width="200">Broj_stranica</td>
                <td width="200">Prosečna_ocena</td>
                <td width="200"></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var v in Model.Knjige)
            {
                <tr>
                    <td>@v.ID_Knjige</td>
                    <td>@v.Naslov</td>
                    <td>@v.Naslov_originala</td>
                    <td>@v.Autor</td>
                    <td>@v.Godina_izdavanja</td>
                    <td>@v.Format_knjige</td>
                    <td>@v.Jezik</td>
                    <td>@v.Zanr</td>
                    <td>@v.Broj_stranica</td>
                    <td>@v.Prosecna_ocena</td>
                    <td>
                        <form action="DeleteKnjiga" method="post">
                            <input type="text" name="id_knjige" placeholder="id_knjige" value="@v.ID_Knjige" hidden="hidden" />
                            <input style="width:100%" type="submit" value="Obriši knjigu" />
                        </form>
                        <form action="UpdateKnjiga" method="post">
                            <input type="text" name="id_knjige" placeholder="id_knjige" value="@v.ID_Knjige" hidden="hidden" />
                            <input style="width:100%" type="submit" value="Izmeni knjigu" />
                        </form>
                        <form asp-action="GoToCreateOcena" method="post" asp-controller="OceneKorisnikaData">
                            <input type="text" name="id_knjige" placeholder="id_knjige" value="@v.ID_Knjige" hidden="hidden" />
                            <input style="width:100%" type="submit" value="Oceni knjigu" />
                        </form>
                        <form asp-action="GoToDodajNaPolicu" method="post" asp-controller="Polica">
                            <input type="text" name="id_knjige" placeholder="id_knjige" value="@v.ID_Knjige" hidden="hidden" />
                            <input style="width:100%" type="submit" value="Dodaj na policu" />
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Aplikacija/Cassandra_GreatReads/Cassandra_GreatReads/Views/KnjigaData/GoToCreateKnjiga.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Cassandra_GreatReads.Models.Knjiga

@{
    ViewBag.Title = "Kreiraj knjigu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model == null)
{
    <div>
        <form action="SaveKnjiga" method="post">
            <label>ID Knjige</label>
            <input type="text" name="id_knjige" placeholder="id_knjige" />
            <br />
            <label>Naslov</label>
            <input type="text" name="naslov" placeholder="naslov" />
            <br />
            <label>Naslov originala</label>
            <input type="text" name="naslov_originala" placeholder="naslov_originala" />
            <br />
            <label>Autor</label>
            <input type="text" name="autor" placeholder="autor" />
            <br />
            <label>Godina izdavanja</label>
            <input type="date" name="godina_izdavanja" placeholder="godina_izdavanja" />
            <br />
            <label>Format knjige</label>
            <input type="text" name="format_knjige" placeholder="format_knjige" />
            <br />
            <label>Jezik</label>
            <input type="text" name="jezik" placeholder="jezik" />
            <br />
            <label>Žanr</label>
            <input type="text" name="zanr" placeholder="zanr" />
            <br />
            <label>Broj stranica</label>
            <input type="text" name="broj_stranica" placeholder="broj_stranica" />
            <br />
            <label hidden="hidden">Prosečna ocena</label>
            <input hidden="hidden" type="text" name="prosecna_ocena" placeholder="prosecna_ocena" value="0" />
            <br />
            <input type="submit" value="Sačuvaj Knjigu" />
        </form>
    </div>
}
else
{
    <div>
        <form action="SaveKnjiga" method="post">
            <label hidden="hidden">ID Knjige</label>
            <input hidden="hidden" type="text" name="id_knjige" placeholder="id_knjige" value="@Model.ID_Knjige" />
            <br />
            <label>Naslov</label>
            <input type="text" name="naslov" placeholder="naslov" value="@Model.Naslov"/>
            <br />
            <label>Naslov originala</label>
            <input type="text" name="naslov_originala" placeholder="naslov_originala" value="@Model.Naslov_originala"/>
            <br />
            <label>Autor</label>
            <input type="text" name="autor" placeholder="autor" value="@Model.Autor"/>
            <br />
            <label>Godina izdavanja</label>
            <input type="date" name="godina_izdavanja" placeholder="godina_izdavanja" value="@Model.Godina_izdavanja"/>
            <br />
            <label>Format knjige</label>
            <input type="text" name="format_knjige" placeholder="format_knjige" value="@Model.Format_knjige"/>
            <br />
            <label>Jezik</label>
            <input type="text" name="jezik" placeholder="jezik" value="@Model.Jezik"/>
            <br />
            <label>Žanr</label>
            <input type="text" name="zanr" placeholder="zanr" value="@Model.Zanr"/>
            <br />
            <label>Broj stranica</label>
            <input type="text" name="broj_stranica" placeholder="broj_stranica" value="@Model.Broj_stranica"/>
            <br />
            <label>Prosečna ocena</label>
            <input type="text" name="prosecna_ocena" placeholder="prosecna_ocena" value="@Model.Prosecna_ocena"/>
            <br />
            <input type="submit" value="Sačuvaj Knjigu" />
        </form>
    </div>
}